name: souffleur
description: A cross platform remote control for presentations
publish_to: 'none'

version: 1.0.0+25090501

environment:
  sdk: ">=3.3.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2
  barcode_scan2: ^4.5.1
  http: ^1.1.0
  shared_preferences: ^2.0.15
  url_launcher: ^6.3.2
  shake: ^3.0.0
  vibration: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  generate: true
  uses-material-design: true
flutter_intl:
  enabled: true
